ConaviWeb/Controllers/CatController.cs
using ConaviWeb.Data.Repositories;
using ConaviWeb.Model;
using ConaviWeb.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using static ConaviWeb.Models.AlertsViewModel;

namespace ConaviWeb.Controllers
{
    public class CatController : Controller
    {
        private readonly ISourceFileRepository _sourceFileRepository;
        private readonly IUserRepository _userRepository;

        public CatController(ISourceFileRepository sourceFileRepository, IUserRepository userRepository)
        {
            _sourceFileRepository = sourceFileRepository;
            _userRepository = userRepository;
        }
        public IActionResult Index()
        {
            return View("../EFirma/_AddItem");
        }

        [HttpPost]
        public async Task<IActionResult> AddItem([FromForm] Partition partition)
        {
            User user = await _userRepository.GetUserDetails(Int32.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            bool success = await _sourceFileRepository.InsertPartition(partition.Text, user);
            if (!success)
            {
                TempData["Alert"] = AlertService.ShowAlert(Alerts.Danger, "Ocurrio un error al registrar la partición");
                return RedirectToAction("Index", "UploadFile");
            }
            TempData["Alert"] = AlertService.ShowAlert(Alerts.Success, "Se registro con exito la partición");
            return RedirectToAction("Index","UploadFile");
        }


    }
}

ConaviWeb/Controllers/EFirmaSatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ConaviWeb.Data.Repositories;
using ConaviWeb.Model;
using ConaviWeb.Model.Request;
using ConaviWeb.Model.Response;
using ConaviWeb.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using static ConaviWeb.Models.AlertsViewModel;

namespace ConaviWeb.Controllers
{
    [Authorize]
    [Route("EFirmaSat")]
    public class EFirmaSatController : Controller
    {
        private readonly IWebHostEnvironment _environment;
        private readonly IUserRepository _userRepository;
        private readonly IProcessSignRepository _processSignRepository;
        private readonly IProcessSigningService _processSigningService;
        public EFirmaSatController(IWebHostEnvironment environment, IUserRepository userRepository, IProcessSignRepository processSignRepository, IProcessSigningService processSigningService)
        {
            _environment = environment;
            _userRepository = userRepository;
            _processSignRepository = processSignRepository;
            _processSigningService = processSigningService;
        }
        public IActionResult Index()
        {
            return View("../EFirma/EFirmaSat");
        }

        [HttpPost]
        public ActionResult Index(string name)
        {
            //Send to the Index Action method which will prevent resubmission.
            return RedirectToAction("Index");
        }

        [Route("/EFirmaSat/SignFiles", Name = "Register")]
        public async Task<IActionResult> SignFiles([FromForm] DataSignRequest dataSignRequest)
        {
            User user = await _userRepository.GetUserDetails(Int32.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            IEnumerable<FileResponse> files;
            bool success = false;
            //if (user.Rol.ToString() == "FirmanteInterno")
            //{
                files = await _processSignRepository.GetFilesForSign(user.IdSystem, dataSignRequest.ArrayFiles);
            //}
            //else
            //{
            //    files = await _processSignRepository.GetExternalFiles(user.Integrador);
            //}
            if (files.Any())
            {
                success = await _processSigningService.ProcessFileSatAsync(user, dataSignRequest, files);
            }
            if (!success)
            {
                TempData["Alert"] = AlertService.ShowAlert(Alerts.Danger, "Error al firmar " + files.Count() + " archivos.");
                //return View("../EFirma/Lista");
                return RedirectToAction("List","Lista");
            }

            TempData["Alert"] = AlertService.ShowAlert(Alerts.Success, "Se firmo " + files.Count() + " archivos.");
            //return View("../EFirma/Lista");
            return RedirectToAction("List", "Lista");
        }


    }
}

ConaviWeb/Controllers/ListCancelController.cs
using ConaviWeb.Data.Repositories;
using ConaviWeb.Model;
using ConaviWeb.Model.Response;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ConaviWeb.Controllers
{
    [Authorize]
    [Route("ListCancel")]
    public class ListCancelController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly IProcessSignRepository _processSignRepository;
        private readonly ISecurityRepository _securityRepository;
        public ListCancelController(IUserRepository userRepository, IProcessSignRepository processSignRepository, ISecurityRepository securityRepository)
        {
            _userRepository = userRepository;
            _processSignRepository = processSignRepository;
            _securityRepository = securityRepository;
        }

        [Route("List")]
        public async Task<IActionResult> Index()
        {
            User user = await _userRepository.GetUserDetails(Int32.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            IEnumerable<Partition> partitions = await _securityRepository.GetPartitions(user.IdSystem);

            ViewData["Partitions"] = partitions;
            if (TempData.ContainsKey("Alert"))
                ViewBag.Alert = TempData["Alert"].ToString();
            return View("../EFirma/ListCancel");
        }

        [HttpGet("ListaFirmadosAjax/{idPartition?}")]
        public async Task<IActionResult> ListAllSigned(int idPartition)
        {
            Response response = new Response();
            User user = await _userRepository.GetUserDetails(Int32.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            IEnumerable<FileResponse> files;

            //if (user.Rol.ToString() == "FirmanteInterno")
            //{
            if (idPartition == 0)
            {
                files = await _processSignRepository.GetSignedFilesCancel(user.IdSystem);
            }
            else
            {
                files = await _processSignRepository.GetPartitionFilesCancel(idPartition);
            }



            //}
            //else
            //{
            //    files = await _processSignRepository.GetExternalFiles(user.Integrador);
            //}

            if (files != null)
            {
                response.Success = 1;
                response.Message = "El usuario cuenta con " + files.Count() + " archivos";
                response.Data = files;
                return Json(new { data = files });
            }

            return BadRequest();
        }
    }
}

ConaviWeb/Controllers/ListSignedFilesController.cs
using ConaviWeb.Data.Repositories;
using ConaviWeb.Model;
using ConaviWeb.Model.Response;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ConaviWeb.Controllers
{
    [Authorize]
    [Route("ListSigned")]
    public class ListSignedFilesController : Controller
    {
        private readonly IWebHostEnvironment _environment;
        private readonly IUserRepository _userRepository;
        private readonly IProcessSignRepository _processSignRepository;
        private readonly ISecurityRepository _securityRepository;

        public ListSignedFilesController(IWebHostEnvironment environment, IUserRepository userRepository, IProcessSignRepository processSignRepository, ISecurityRepository securityRepository)
        {
            _environment = environment;
            _userRepository = userRepository;
            _processSignRepository = processSignRepository;
            _securityRepository = securityRepository;
        }
        [Route("List")]
        public async Task<IActionResult> Index()
        {
            User user = await _userRepository.GetUserDetails(Int32.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            IEnumerable<Partition> partitions = await _securityRepository.GetPartitions(user.IdSystem);

            ViewData["Partitions"] = partitions;
            return View("../EFirma/ListFirmados");
        }

        [HttpGet("ListaFirmadosAjax/{idPartition?}")]
        public async Task<IActionResult> ListAllSigned(int idPartition)
        {
            Response response = new Response();
            User user = await _userRepository.GetUserDetails(Int32.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            IEnumerable<FileResponse> files;

            //if (user.Rol.ToString() == "FirmanteInterno")
            //{
                if (idPartition == 0)
                {
                    files = await _processSignRepository.GetSignedFiles(user.IdSystem);
                }
                else
                {
                    files = await _processSignRepository.GetPartitionFiles(idPartition);
                }
                


            //}
            //else
            //{
            //    files = await _processSignRepository.GetExternalFiles(user.Integrador);
            //}

            if (files != null)
            {
                response.Success = 1;
                response.Message = "El usuario cuenta con " + files.Count() + " archivos";
                response.Data = files;
                return Json(new { data = files });
            }

            return BadRequest();
        }
        [Route("DownloadZipFile/{id?}")]
        public async Task DownloadZipFile(int id)
        {
            Partition partition = await _securityRepository.GetPartition(id);

            Response.ContentType = "application/octet-stream";
            DateTime date = DateTime.Now;
            Response.Headers.Add("Content-Disposition", "attachment; filename=\"Files"+date.ToString("ddMMyyyy") +".zip\"");

            var botsFolderPath = Path.Combine(_environment.WebRootPath, partition.PathPartition ,partition.Text);
            var botFilePaths = Directory.GetFiles(botsFolderPath);
            using (ZipArchive archive = new ZipArchive(Response.BodyWriter.AsStream(), ZipArchiveMode.Create))
            {
                foreach (var botFilePath in botFilePaths)
                {
                    var botFileName = Path.GetFileName(botFilePath);
                    var entry = archive.CreateEntry(botFileName);
                    using (var entryStream = entry.Open())
                    using (var fileStream = System.IO.File.OpenRead(botFilePath))
                    {
                        await fileStream.CopyToAsync(entryStream);
                    }
                }
            }
        }
    }
}

ConaviWeb/Controllers/ListaController.cs
using ConaviWeb.Data.Repositories;
using ConaviWeb.Model;
using ConaviWeb.Model.Response;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ConaviWeb.Controllers
{
    [Authorize]
    [Route("Lista")]
    public class ListaController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly IProcessSignRepository _processSignRepository;

        public ListaController(IUserRepository userRepository, IProcessSignRepository processSignRepository)
        {
            _userRepository = userRepository;
            _processSignRepository = processSignRepository;
        }
        [Route("List")]
        public IActionResult Index()
        {
            if (TempData.ContainsKey("Alert"))
                ViewBag.Alert = TempData["Alert"].ToString();
            return View("../EFirma/Lista");
        }

        [HttpGet("ListaAjax")]
        public async Task<IActionResult> ListAllFiles()
        {
            Response response = new Response();
            User user = await _userRepository.GetUserDetails(Int32.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            IEnumerable<FileResponse> files;

            //if (user.Rol.ToString() == "FirmanteInterno")
            //{
                files = await _processSignRepository.GetFiles(user.IdSystem);


            //}
            //else
            //{
            //    files = await _processSignRepository.GetExternalFiles(user.Integrador);
            //}

            if (files != null)
            {
                response.Success = 1;
                response.Message = "El usuario cuenta con " + files.Count() + " archivos";
                response.Data = files;
                return Json(new { data=files });
            }

            return BadRequest();
        }

        [HttpGet("ListDetailAjax/{idPartition?}")]
        public async Task<IActionResult> ListDetailFiles(int idPartition)
        {
            Response response = new Response();
            IEnumerable<FileResponse> files;

            //if (user.Rol.ToString() == "FirmanteInterno")
            //{
            files = await _processSignRepository.GetPartitionSourceFiles(idPartition);


            //}
            //else
            //{
            //    files = await _processSignRepository.GetExternalFiles(user.Integrador);
            //}

            if (files != null)
            {
                response.Success = 1;
                response.Message = "El usuario cuenta con " + files.Count() + " archivos";
                response.Data = files;
                return Json(new { data = files });
            }

            return BadRequest();
        }
    }
}

ConaviWeb/Controllers/RH/ListaController.cs
using ConaviWeb.Commons;
using ConaviWeb.Data.RH;
using ConaviWeb.Model.Response;
using ConaviWeb.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ConaviWeb.Controllers.RH
{
    public class ListaController : Controller
    {
        private readonly IRHRepository _rHRepository;
        private readonly IMailService _mailService;
        public ListaController(IRHRepository rHRepository, IMailService mailService)
        {
            _rHRepository = rHRepository;
            _mailService = mailService;
        }
        public IActionResult Index()
        {
            return View("../RH/ListaSolicitudes");
        }
        public async Task<IActionResult> GetSolicitudesAsync()
        {
            var user = HttpContext.Session.GetObject<UserResponse>("ComplexObject");
            var solicitudes = await _rHRepository.GetSolicitudesUser(user.Id);
            return Json(new { data = solicitudes });
        }
    }
}

ConaviWeb/Views/EFirma/CancelaSat.cshtml
@model ConaviWeb.Model.Request.DataSignRequest
@{
    ViewBag.Title = "Cancelación";
}
@*<div class="spinner" style="display:none">
    <div class="center-div">
        <div class="inner-div">
            <div class="loader"></div>
        </div>
    </div>
</div>*@

<div class="form-group row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-body">
                <form id="formSign" class="submit-once" enctype="multipart/form-data" method="post" asp-route="Cancel">
                    <div class="alert alert-danger" asp-validation-summary="ModelOnly"><button class="close" data-dismiss="alert" aria-hidden="true">&times;</button></div>
                    <div class="form-group">
                        <label asp-for="KeySat"></label>
                        <input asp-for="KeySat" type="file" accept=".key">
                        <span asp-validation-for="KeySat" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CerSat"></label>

                        <input asp-for="CerSat" type="file" accept=".cer">
                        <span asp-validation-for="CerSat" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PassFirmante"></label>
                    </div>
                    <div class="form-group">
                        <input class="form-control" asp-for="PassFirmante" />
                        <span asp-validation-for="PassFirmante" class="text-danger"></span>
                    </div>
                    @*<label asp-for="ArrayFiles"></label>*@
                    <div class="form-group">
                        <input class="form-control" id="arrayCHK" type="hidden" asp-for="ArrayFiles" readonly />
                        <span asp-validation-for="ArrayFiles" class="text-danger"></span>
                    </div>
                    <button type="submit" id="btnFirma" class="btn btn-primary pull-right"><span class="fa fa-exclamation-triangle"></span>&ensp;Cancelar Firma</button>
                </form>
            </div>
        </div>
    </div>
</div>
        @section Scripts {@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}}

ConaviWeb/Views/EFirma/EFirmaSat.cshtml
@model ConaviWeb.Model.Request.DataSignRequest
@{
    ViewBag.Title = "EFirma";
}

<div class="form-group row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-body">
                <form id="formSign" class="submit-once" enctype="multipart/form-data" method="post" asp-route="Register">
                    <div class="alert alert-danger" asp-validation-summary="ModelOnly"><button class="close" data-dismiss="alert" aria-hidden="true">&times;</button></div>
                    <div class="form-group">
                        <label asp-for="KeySat"></label>
                        <input asp-for="KeySat" type="file" accept=".key">
                        <span asp-validation-for="KeySat" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CerSat"></label>
                        <input asp-for="CerSat" type="file" accept=".cer">
                        <span asp-validation-for="CerSat" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PassFirmante"></label>
                        <input class="form-control" asp-for="PassFirmante" />
                        <span asp-validation-for="PassFirmante" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        @*<label asp-for="ArrayFiles"></label>*@
                        <input class="form-control" id="arrayCHK" type="hidden" asp-for="ArrayFiles" readonly />
                        <span asp-validation-for="ArrayFiles" class="text-danger"></span>
                    </div>
                    <button type="submit" id="btnFirma" class="btn btn-primary pull-right"><span class="fa fa-check"></span>&ensp;Firmar</button>
                </form>
            </div>
        </div>
    </div>
</div>
        @section Scripts {@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}}

ConaviWeb/Views/EFirma/ListFirmados.cshtml
@model ConaviWeb.Model.Request.FileRequest
@{
    ViewBag.Title = "Archivos Firmados";
}
<div class="panel panel-default">
    <div class="panel-body">
        <div class="form-row">
            <div class="form-group col-md-6">
                <div id="spinner" class="spinner-border text-primary" role="status">
                    <span class="sr-only">Loading...</span>
                </div>
            </div>
            @*<a id="btnAddProcedure" asp-controller="ListSignedFiles" asp-action="DownloadZipFile">Descargar</a>*@
            <div class="form-group col-md-6 divUpload">
                <a class="btn btn-primary pull-right" id="btnAddProcedure" asp-controller="ListSignedFiles" asp-action="DownloadZipFile"><span class="fa fa-cloud-download"></span>&ensp;Descargar</a>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                <label asp-for="Partition"></label>
                <select id="slctPartition" name="slctPartition" class="form-control" asp-for="Partition" asp-items="@(new SelectList((System.Collections.IEnumerable)ViewData["Partitions"], "Id" , "Text" ))">
                    <option value="0">--Select--</option>
                </select>
            </div>
        </div>
    </div>
</div>
<hr />
<br />
<div class="row">
    <div class="col-md-12">
        <form id="formTable">
            <table id="table" class="table">
                <thead>
                    <tr>
                        <th>
                            ID
                        </th>
                        <th>
                            RUTA
                        </th>
                        <th>
                            NOMBRE
                        </th>
                        <th>
                            FECHA CARGA
                        </th>
                        <th>
                            ESTATUS
                        </th>
                        <th>
                            DETALLE
                        </th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </form>
    </div>
</div>



<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        var table;
        $(document).ready(function () {
            $("#spinner").hide();
            showTable(0);
            var oldref = $("#btnAddProcedure").attr('href');
            $("#btnAddProcedure").attr('href','#');
            $('#slctPartition').on('change', function () {
                var textValue = this.value;
                if (textValue == 0) {
                    $("#btnAddProcedure").attr('href', '#');
                } else {
                    //console.log(textValue);
                    var newhref = oldref + '/' + textValue;
                    //console.log(newhref);

                    $("#btnAddProcedure").attr("href", newhref);
                }

                showTable(textValue);
            });
        });

        function showTable(textValue) {
            $("#spinner").show();
            table = $('#table').DataTable({
                "proccessing": true,
                "serverSide": false,
                "ajax": {
                    url: "/ListSigned/ListaFirmadosAjax" + '/' + textValue,
                    type: 'GET',
                    headers: { 'RequestVerificationToken': $('@Html.AntiForgeryToken()').val() },
                    complete: function () {
                        $("#spinner").hide();
                    }
                },
                "columnDefs": columns,
                "order": [0],
                "autoWidth": true,
                "destroy": true,
                "scrollY": '700px',
                "scrollCollapse": true,
                "paging": true,
                "info": true,
                "buttons": ['excel'],
                "scrollX": true,
                "fixedColumns": true,
                "ordering": false,
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    }
                }
            });
        }
        var columns = [
            {
                "targets": -1,
                "data": null,
                "render": function (data, type, row, meta) {
                    //return '<a href="/customers/edit/' + row.id + '">Edit</a> | <a href="/customers/details/' + row.id + '">Details</a> | <a href="/customers/delete/' + row.id + '">Delete</a>';
                    return '<a href="../' + row.filePath + "/" + row.fileName + '" target="_blank"><i class="fa fa-file-pdf-o gold" style="font-size:25px;"></i></a>';
                },
                "sortable": false,
                "className": 'text-center'
            },
            { "name": "Id", "data": "id", "targets": 0, "visible": false },
            { "name": "FilePath", "data": "filePath", "targets": 1 },
            { "name": "FileName", "data": "fileName", "targets": 2 },
            { "name": "DateUpload", "data": "dateUpload", "targets": 3 },
            { "name": "Status", "data": "status", "targets": 4 }
        ];

    </script>
}

ConaviWeb/Views/EFirma/_AddItems.cshtml
@model ConaviWeb.Model.Partition
<script src="~/js/jquery-1.11/jquery.min.js" type="text/javascript"></script>

<form id="formPartition" method="post" asp-controller="Cat" asp-action="AddItem">
    <div class="alert alert-danger" asp-validation-summary="ModelOnly"><button class="close" data-dismiss="alert" aria-hidden="true">&times;</button></div>
    @*<div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">Agregar nueva partición</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Text"></label>
                    <input id="partitionText" class="form-control" asp-for="Text" autocomplete="off" />
                    <span asp-validation-for="Text" class="text-danger"></span>

                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>*@
    

        <div class='modal-header'>
            <h4 id='titulo-modal' style="font-weight: 300">Agregar nueva partición</h4>
        </div>
        <div class='modal-body' style="height: 200px; overflow-x: hidden; overflow-y: auto;">
            <div class="row col-md-12">
                    <label asp-for="Text" style="font-size:18px"></label>
                    <input id="partitionText" class="form-control" asp-for="Text" autocomplete="off" />
                    <span asp-validation-for="Text" class="text-danger"></span>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
</form>



@section scripts{@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}}

ConaviWeb/Views/EFirma/_ListaCargados.cshtml
@{
    ViewBag.Title = "Lista Cargados";
}
    <form id="formTable">
        <table id="table" class="table">
            <thead>
                <tr>
                    <th>
                        ID
                    </th>
                    <th>
                        RUTA
                    </th>
                    <th>
                        NOMBRE
                    </th>
                    <th>
                        FECHA CARGA
                    </th>
                    <th>
                        ESTATUS
                    </th>
                    <th>
                        DETALLE
                    </th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </form>
<br />
<br />
<br />