ConaviWeb/Controllers/RH/ActividadController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConaviWeb.Controllers.RH
{
    public class ActividadController : Controller
    {
        public IActionResult Index()
        {
            return View("../RH/Actividad");
        }
    }
}

ConaviWeb/Controllers/RH/CargaRecibosNController.cs
using ConaviWeb.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using static ConaviWeb.Models.AlertsViewModel;

namespace ConaviWeb.Controllers.RH
{
    public class CargaRecibosNController : Controller
    {
        private readonly IWebHostEnvironment _environment;

        public CargaRecibosNController(IWebHostEnvironment environment)
        {
            _environment = environment;
        }
        public IActionResult Index()
        {
            if (TempData.ContainsKey("Alert"))
                ViewBag.Alert = TempData["Alert"].ToString();
            return View("../RH/CargaRecibosN");
        }

        [HttpPost]
        [DisableRequestSizeLimit,
        RequestFormLimits(MultipartBodyLengthLimit = int.MaxValue,
        ValueLengthLimit = int.MaxValue)]
        public IActionResult UpLoad()
        {
            var files = Request.Form.Files;
            var json = Request.Form["json"].ToString();
            var data = JObject.Parse(json);
            var anio = data.GetValue("anio").ToString();
            var periodo = data.GetValue("periodo").ToString();
            string alert;
            string[] arrperiodo = periodo.Split(@"-");
            try
            {
                foreach (var file in files)
                {
                    string[] arrpath = file.FileName.Split(@"/");
                    string dirpath = "";//Directory where the file is located (including one or two levels of directories)
                    string fulldir = Path.Combine(arrpath[arrpath.Length - 2].ToString(), arrpath[arrpath.Length - 1].ToString());
                    string filename = arrpath[arrpath.Length - 1].ToString();//The file name
                    var extension = Path.GetExtension(filename);
                    if (!extension.Contains(".pdf") && !extension.Contains(".xml"))
                    {
                        alert = AlertService.ShowAlert(Alerts.Danger, "Solo están permitidos archivos con extensión .pdf y .xml");
                        return Ok(new
                        {
                            success = false,
                            message = alert
                        });
                    }
                    string rootpath = Path.Combine(_environment.WebRootPath, "doc", "RH", "ReciboNomina", anio, arrperiodo[0], arrperiodo[1]);
                    for (int i = 1; i < arrpath.Length; i++)
                    {
                        if (i == arrpath.Length - 1)
                        {
                            break;
                        }
                        dirpath += arrpath[i] + @"/";
                    }

                    dirpath = Path.Combine(rootpath, dirpath);
                        DicCreate(dirpath);//Create the directory if it does not exist


                    string filepath = Path.Combine(rootpath, fulldir);
                    using (var addFile = new FileStream(filepath, FileMode.OpenOrCreate))
                    {
                        if (file != null)
                        {
                            file.CopyTo(addFile);
                        }
                        else
                        {
                            Request.Body.CopyTo(addFile);
                        }
                        addFile.Close();
                    }
                }
                alert = AlertService.ShowAlert(Alerts.Success, "Se cargaron " + files.Count + " archivos" );
                return Ok(new
                {
                    success = true,
                    message = alert
                });
            }
            catch (Exception ex)
            {
                alert = AlertService.ShowAlert(Alerts.Danger, "Ocurrio un error al cargar los archivos");
                return Ok(new
                {
                    success = false,
                    message = alert
                });
            }
        }
        /// <summary>
        /// If the file directory does not exist, create a new directory
        /// </summary>
        /// <param name="path"></param>
        private void DicCreate(string path)
        {
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
        }
    }
}

ConaviWeb/Controllers/RH/ContasSolicitudController.cs
using ConaviWeb.Data.RH;
using ConaviWeb.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static ConaviWeb.Models.AlertsViewModel;

namespace ConaviWeb.Controllers.RH
{
    public class ContasSolicitudController : Controller
    {
        private readonly IRHRepository _rHRepository;
        private readonly IWebHostEnvironment _environment;
        public ContasSolicitudController(IRHRepository rHRepository, IWebHostEnvironment environment)
        {
            _rHRepository = rHRepository;
            _environment = environment;
        }
        public IActionResult Index()
        {
            if (TempData.ContainsKey("Alert"))
                ViewBag.Alert = TempData["Alert"].ToString();
            return View("../RH/ContasSolicitud");
        }
        [HttpGet]
        public async Task<IActionResult> GetSolicitudesAsync()
        {

            var success = await _rHRepository.GetSolicitudes(3);
            if (!success.Any())
            {
                return BadRequest();
            }
            return Json(new { data = success });
        }
        public async Task<IActionResult> VoBoContasAsync(int id)
        {
            var success = await _rHRepository.UpdateEstatus(id,4);
            if (!success)
            {
                TempData["Alert"]=AlertService.ShowAlert(Alerts.Danger, "Ocurrio un error al actualizar estatus");
                return RedirectToAction("Index");
            }
            TempData["Alert"]=AlertService.ShowAlert(Alerts.Success, "Se verifico la solicitud con exito");
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> CancelarSolicitudAsync(string obs, int idReg)
        {
            
            var success = await _rHRepository.UpdateEstatus(idReg, 9, obs);
            if (!success)
            {
                TempData["Alert"] = AlertService.ShowAlert(Alerts.Danger, "Ocurrio un error al actualizar estatus");
                return RedirectToAction("Index");
            }
            TempData["Alert"] = AlertService.ShowAlert(Alerts.Success, "Se actualizo la solicitud con exito");
            return RedirectToAction("Index");
        }
    }
}

ConaviWeb/Controllers/RH/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConaviWeb.Controllers.RH
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View("../RH/Index");
        }
    }
}

ConaviWeb/Controllers/RH/HomeRHController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConaviWeb.Controllers.RH
{
    public class HomeRHController : Controller
    {
        public IActionResult Index()
        {
            return View("../RH/Index");
        }
    }
}

ConaviWeb/Controllers/RH/ListaComprobacionController.cs
using ConaviWeb.Commons;
using ConaviWeb.Data.RH;
using ConaviWeb.Model.Response;
using ConaviWeb.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ConaviWeb.Controllers.RH
{
    public class ListaComprobacionController : Controller
    {
        private readonly IRHRepository _rHRepository;
        private readonly IMailService _mailService;
        public ListaComprobacionController(IRHRepository rHRepository, IMailService mailService)
        {
            _rHRepository = rHRepository;
            _mailService = mailService;
        }
        public IActionResult Index()
        {
            return View("../RH/ListaComprobacion");
        }
        public async Task<IActionResult> GetSolicitudesAsync()
        {
            var user = HttpContext.Session.GetObject<UserResponse>("ComplexObject");
            var solicitudes = await _rHRepository.GetSolicitudesUser(user.Id,4);
            return Json(new { data = solicitudes });
        }
    }
}

ConaviWeb/Controllers/RH/ListaController.cs
using ConaviWeb.Commons;
using ConaviWeb.Data.RH;
using ConaviWeb.Model.Response;
using ConaviWeb.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ConaviWeb.Controllers.RH
{
    public class ListaController : Controller
    {
        private readonly IRHRepository _rHRepository;
        private readonly IMailService _mailService;
        public ListaController(IRHRepository rHRepository, IMailService mailService)
        {
            _rHRepository = rHRepository;
            _mailService = mailService;
        }
        public IActionResult Index()
        {
            return View("../RH/ListaSolicitudes");
        }
        public async Task<IActionResult> GetSolicitudesAsync()
        {
            var user = HttpContext.Session.GetObject<UserResponse>("ComplexObject");
            var solicitudes = await _rHRepository.GetSolicitudesUser(user.Id);
            return Json(new { data = solicitudes });
        }
    }
}

ConaviWeb/Controllers/RH/RecibosNominaController.cs
using ConaviWeb.Commons;
using ConaviWeb.Data.RH;
using ConaviWeb.Model.Response;
using ConaviWeb.Model.RH;
using ConaviWeb.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using static ConaviWeb.Models.AlertsViewModel;

namespace ConaviWeb.Controllers.RH
{
    public class RecibosNominaController : Controller
    {
        private readonly IWebHostEnvironment _environment;
        private readonly INominaRepository _nominaRepository;

        public RecibosNominaController(IWebHostEnvironment environment, INominaRepository nominaRepository)
        {
            _environment = environment;
            _nominaRepository = nominaRepository;
        }
        public IActionResult Index()
        {
            if (TempData.ContainsKey("Alert"))
                ViewBag.Alert = TempData["Alert"].ToString();
            return View("../RH/RecibosNomina");
        }
        public async Task<IActionResult> DownloadZipRN(string anio, string periodo, string acept)
        {
            string[] arrperiodo = periodo.Split(@"-");
                string[] meses = {"Enero",
                                    "Febrero",
                                    "Marzo",
                                    "Abril",
                                    "Mayo",
                                    "Junio",
                                    "Julio",
                                    "Agosto",
                                    "Septiembre",
                                    "Octubre",
                                    "Noviembre",
                                    "Diciembre"};
                var numes = Array.FindIndex(meses, row => row.Contains(arrperiodo[0])) + 1;
            var rootPath = Path.Combine(_environment.WebRootPath, "doc", "RH", "ReciboNomina");

            var user = HttpContext.Session.GetObject<UserResponse>("ComplexObject");

            var botsFolderPath = Path.Combine(rootPath, anio, arrperiodo[0], arrperiodo[1], user.NuEmpleado);
            var zipFileMemoryStream = new MemoryStream();
            try
            {
                var botFilePaths = Directory.GetFiles(botsFolderPath);

                using (ZipArchive archive = new ZipArchive(zipFileMemoryStream, ZipArchiveMode.Update, leaveOpen: true))
                {
                    foreach (var botFilePath in botFilePaths)
                    {
                        var botFileName = Path.GetFileName(botFilePath);
                        var entry = archive.CreateEntry(botFileName);
                        using (var entryStream = entry.Open())
                        using (var fileStream = System.IO.File.OpenRead(botFilePath))
                        {
                            await fileStream.CopyToAsync(entryStream);
                        }
                    }
                }

               
                Aceptacion aceptacion = new();
                aceptacion.Anio = anio;
                aceptacion.Mes = numes.ToString();
                aceptacion.Quincena = arrperiodo[1].Substring(1);
                aceptacion.Acepta = acept.Equals("on") ? 1 : 2;
                aceptacion.NuEmpleado = user.NuEmpleado;

                var success = await _nominaRepository.InsertAceptacion(aceptacion);
            }
            catch (Exception e)
            {
                TempData["Alert"] = AlertService.ShowAlert(Alerts.Danger, "El periodo consultado no cuenta con archivos");
                return RedirectToAction("Index");
            }
            zipFileMemoryStream.Seek(0, SeekOrigin.Begin);
            return File(zipFileMemoryStream, "application/octet-stream", "Recibo_" + anio + arrperiodo[0] + arrperiodo[1] + ".zip");
        }
    }
}

ConaviWeb/Views/RH/CargaRecibosN.cshtml
@{
    ViewData["Title"] = "Carga";
}
<div class="form-row">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="form-group col-md-4">
                    <div id="spinner" class="spinner-border text-primary" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <div class="form-group" id="alert">
                        @Html.Raw(@ViewBag.Alert)
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <button class="btn btn-primary pull-right" id="upload" type="button" onclick="Upload()"><i class="fa fa-cloud-upload" aria-hidden="true"></i> Cargar</button>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label>Año</label>
                    <select id="slctAnio" class="form-control" name="anio">
                    </select>
                    
                </div>
                <div class="form-group col-md-4">
                    <label>Periodo Mes</label>
                    <select id="slctPeriodo" class="form-control" name="periodo">
                    </select>
                </div>
                <div class="form-group col-md-4">
                    <label>Archivos</label>
                    <input type="file" class="form-control-file" name="file" webkitdirectory>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var files = [];
    $(document).ready(function () {
        getAnio();
        getQuincena();
        $('input').change(function () {
            files = this.files;
        })
        $('#spinner').hide();
    });

    function Upload() {
        debugger
        let ganio = $("#slctAnio option:selected").text();
        let gperiodo = $("#slctPeriodo option:selected").text();
        let obj = {
            anio: ganio,
            periodo: gperiodo,
        };
        let json = JSON.stringify(obj);
        $('#spinner').show();
        var data = new FormData();
        data.append("json", json);
        
        for (var i = 0; i < files.length; i++) {
            data.append('file', files[i]);
        }
        var path = files[0].webkitRelativePath;
        $.ajax({
            type: "post",
            url: "@Url.Action("Upload", "CargaRecibosN")", // Url
            data: data,
            processData: false,
            contentType: false,
            success: function (data) {
                $('#spinner').hide();
                $("#alert").html(data.message).fadeIn("slow");
                showAlert();
            }
        })
    }
    function showAlert() {

        setTimeout(function () {
            $("#alerta").fadeOut(1500);

        }, 3000);


        setTimeout(function () {

            $("#alerta").remove();
        }, 6000);

    }

    function getAnio() {
        var optionString = '';
        var data = [];
        // Return today's date and time
        var currentTime = new Date()

        // returns the nimus year (four digits)
        var before = currentTime.getFullYear() - 1;

        // returns the year (four digits)
        var year = currentTime.getFullYear();

        // returns the max year (four digits)
        var after = currentTime.getFullYear() + 1;

        data.push(before, year, after);

        data.forEach(function (dataItem, index) {
            optionString += '<option value="' + dataItem + '">' + dataItem + '</option>';
        });

        $('#slctAnio').append(optionString);
    }

    function getQuincena() {
        var optionString = '';
        var data =
            ["Enero-01",
                "Enero-02",
                "Febrero-01",
                "Febrero-02",
                "Marzo-01",
                "Marzo-02",
                "Abril-01",
                "Abril-02",
                "Mayo-01",
                "Mayo-02",
                "Junio-01",
                "Junio-02",
                "Julio-01",
                "Julio-02",
                "Agosto-01",
                "Agosto-02",
                "Septiembre-01",
                "Septiembre-02",
                "Octubre-01",
                "Octubre-02",
                "Noviembre-01",
                "Noviembre-02",
                "Diciembre-01",
                "Diciembre-02"];

        data.forEach(function (dataItem, index) {
            optionString += '<option value="' + dataItem + '">' + dataItem + '</option>';
        });

        $('#slctPeriodo').append(optionString);
    }
</script>

ConaviWeb/Views/RH/Index.cshtml
@{
    ViewData["Title"] = "Inicio";
}
hello home

ConaviWeb/Views/RH/ListaComprobacion.cshtml
@model ConaviWeb.Model.Sisevive.Etiquetado
@{

    ViewBag.Title = "Solicitudes";
}


<div class="row">
    <div class="form-group col-md-4">
        <div id="spinner" class="spinner-border text-primary" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <div class="form-group col-md-4">
        <div id="alertAjax" class="form-group">
            @Html.Raw(@ViewBag.Alert)
        </div>
    </div>
    <div class="form-group col-md-4">
        @*<a href="@Url.Action("GetAllBenef", "PevC2sr")"><i class="fa fa-file-pdf-o gold" style="font-size:25px;"></i></a>*@
    </div>
</div>

<div id="divTable" class="form-group" style="display:none;">
    <form id="formTable">
        <table id="table" class="table" style="width: 100%">
            <thead>
                <tr style="font-size:15px;">
                    <th>
                        ID
                    </th>
                    <th>
                        FECHA
                    </th>
                    <th>
                        # COMISIÓN
                    </th>
                    <th>
                        ESTATUS
                    </th>
                    <th>
                        ARCHIVO
                    </th>
                    <th>
                        EDITAR
                    </th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </form>
</div>
<div id="partial" class="row col-md-12 hidden">
    @{
        @await Html.PartialAsync("../RH/_ComprobacionDetail")
    }
</div>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script>
    var table;
    //var dataJSON;
        $(document).ready(function () {
            showAlert();
            $("#spinner").hide();
            //showAlert();
            //var tipo = $("#slctTipo option:selected").val();
            showTable();
            //console.log(dataJSON);

            /*$('#slctTipo').on('change', function () {
                console.log(this.value);
                showTable(this.value);
            });*/
            $('body').on('click', 'a', function (e) {
                //showTableC();
                if (this.className === "gold btn-action") {
                    let json = this.id.replace(/'/g, '"');
                    json = JSON.parse(json);
                    getComprobaciones(json.folio);
                    var idUser;
                    //console.log(json);
                    $.each(json, function (id, valor) {
                        //console.log(valor,id)
                        //console.log("$('#' ", id+").val("+valor+");");
                        //$("#" + id).attr("value", valor);

                        if (valor != null) {
                            //console.log(id, ":", valor);
                            if (id == "id") {
                                $("#" + id).val(valor);
                            } else if (id == "idUsuario") {
                                idUser = valor;
                                //console.log("usuario: ", idUser);
                            } else if (id == "traza_ruta") {
                                //console.log("usuario: ", idUser);
                                let foo = valor.indexOf("_")
                                $("#" + id).attr("src", "/doc/RH/SolicitudViaticos/" + valor.substring(0, foo) + "/" + valor);
                            } else {
                                $("#" + id).text(valor);
                            }

                        } else {
                            $("#" + id).text("");
                        }
                        //$("#" + id).attr("disabled", true);
                    });

                    $("#partial").removeClass("hidden");
                    scroll("partial");
                }


            });
        });

        function showTable() {

            $("#spinner").show();
            $("#divTable").show();
            table = $('#table').DataTable({
                "proccessing": true,
                "serverSide": false,
                "ajax": {
                    url: "@Url.Action("GetSolicitudes", "ListaComprobacion")",
                    //url: "/AdminSolicitud/GetSolicitudes",
                    type: 'GET',
                    headers: { 'RequestVerificationToken': $('@Html.AntiForgeryToken()').val() },
                    //success: function (data) { console.log(data) },
                    complete: function () {
                        $("#spinner").hide();
                        //dataJSON = data.responseJSON.data;
                        //console.log(data);
                    }
                },
                "columnDefs": columns,
                "order": [[0, "desc"]],
                "autoWidth": true,
                "destroy": true,
                "scrollY": '700px',
                "scrollCollapse": true,
                "paging": true,
                "info": true,
                "buttons": ['excel'],
                "scrollX": true,
                "fixedColumns": true,
                "ordering": false,
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    }
                }
            });
        }

        var columns = [

            { "name": "Id", "data": "id", "targets": 0, "visible": false},
            { "name": "Fecha", "data": "fechaSol", "targets": 1 },
            { "name": "Folio", "data": "folio", "targets": 2 },
            { "name": "Estatus", "data": "estatus", "targets": 3 },
            {
                "targets": 4,
                "data": null,
                "render": function (data, type, row, meta) {
                    if (row.estatus >= 3) {
                        return '<a href="https://firmaelectronica.conavi.gob.mx:9090/doc/EFirma/Firmado/Recursos_Humanos/' + row.archivo_firma +'" target="_blank"><i class="fa fa-file-pdf-o gold" style="font-size:25px;"></i></a>';
                    }
                    return '<a href="../AdminSolicitud/GenerateStreamPDF?id=' + row.id + '" target="_blank"><i class="fa fa-file-pdf-o gold" style="font-size:25px;"></i></a>';
                },
                "sortable": false,
                "className": 'text-center'
            }, {
                "targets": 5,
                "data": null,
                "render": function (data, type, row, meta) {
                    let json = JSON.stringify(row);
                    //console.log(json.folio);
                    json = json.replace(/"/g, "'");
                    if (row.estatus == 4) {

                        return '<a id="' + json + '" class="gold btn-action" elemento="" type="button" style="font-size:25px;" data-toggle="tooltip" title="Editar"><i class="fa fa-pencil-square-o"></i></a>';
                    }
                    return "";
                },
                "sortable": false,
                "className": 'text-center'
            },

        ];

        function showAlert() {
            scroll("partialView");
            setTimeout(function () {

                $("#alerta").fadeOut(1500);

            }, 6000);


            setTimeout(function () {

                $("#alerta").remove();
            }, 12000);

        }

        function scroll(id) {
            try {
                let el = document.getElementById(id);
                el.scrollIntoView(true);
            } catch (e) { console.log(e) }
        }

        


</script>
}