ConaviWeb/Controllers/Expedientes/BibliohemerograficoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ConaviWeb.Commons;
using ConaviWeb.Data.Expedientes;
using ConaviWeb.Model.Expedientes;
using ConaviWeb.Services;
using static ConaviWeb.Models.AlertsViewModel;
using ConaviWeb.Model.Response;
using ConaviWeb.Model;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ConaviWeb.Controllers.Expedientes
{
    public class BibliohemerograficoController : Controller
    {
        private readonly IExpedienteRepository _expedienteRepository;
        public BibliohemerograficoController(IExpedienteRepository expedienteRepository)
        {
            _expedienteRepository = expedienteRepository;
        }
        public async Task<IActionResult> IndexAsync()
        {
            var user = HttpContext.Session.GetObject<UserResponse>("ComplexObject");
            var idUserPuesto = await _expedienteRepository.GetIdUserPuesto(user.Cargo);
            var inventario = await _expedienteRepository.GetInventarioBibliohemerografico(user.Cargo);
            var cat = await _expedienteRepository.GetTiposSoporte();
            ViewData["Catalogo"] = cat;
            //var catArea = await _expedienteRepository.GetAreas();
            //ViewBag.AreaCatalogo = (new SelectList(catArea, "Id", "Clave", idUserArea));
            ViewBag.NombreResponsable = inventario != null ? inventario.NombreResponsableAT : "";
            ViewBag.IdInv = inventario != null ? inventario.Id : 0;
            //ViewBag.FechaElab = inventario != null ? inventario.FechaElaboracion.ToString("dd/MM/yyyy") : "";
            ViewBag.FechaElab = inventario != null ? inventario.FechaElaboracion : "";
            ViewBag.FechaTrans = inventario != null ? inventario.FechaTransferencia : "";
            int rol = (int)user.Rol;
            if (rol == 15)
            {
                var catPuesto = await _expedienteRepository.GetPuestosLista();
                ViewBag.AreaCatalogo = (new SelectList(catPuesto, "IdPuesto", "Puesto", idUserPuesto));
                //ViewData["btnShowValidacion"] = true;
            }
            else
            {
                var catPuesto = await _expedienteRepository.GetPuestoUser(idUserPuesto);
                ViewBag.AreaCatalogo = new SelectList(catPuesto, "IdPuesto", "Puesto", idUserPuesto);
                //ViewData["btnShowValidacion"] = false;
            }
            if (TempData.ContainsKey("Alert"))
                ViewBag.Alert = TempData["Alert"].ToString();
            return View("../Expedientes/Bibliohemerografico");
        }
        [HttpPost]
        public async Task<IActionResult> InsertInventarioBibliohemerografico(Inventario inventario)
        {
            var success = await _expedienteRepository.InsertInventarioBibliohemerografico(inventario);
            if (!success)
            {
                TempData["Alert"] = AlertService.ShowAlert(Alerts.Danger, "Ocurrio un error al registrar el inventario");
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> GetInventarioBibliohemerografico([FromForm] string puesto)
        {
            Inventario inventario = new();
            inventario = await _expedienteRepository.GetInventarioBibliohemerografico(puesto);
            if (inventario == null)
            {
                var alert = AlertService.ShowAlert(Alerts.Danger, "Id de inventario no encontrado");
                return Ok(alert);
            }
            return Ok(inventario);
        }
        [HttpPost]
        public async Task<IActionResult> GetInventarioBiblioById([FromForm] int id)
        {
            Inventario inventario = new();
            inventario = await _expedienteRepository.GetInventarioBiblioById(id);
            if (inventario == null)
            {
                var alert = AlertService.ShowAlert(Alerts.Danger, "Id de inventario no encontrado");
                return Ok(alert);
            }
            return Ok(inventario);
        }
        [HttpPost]
        public async Task<IActionResult> InsertExpedienteBibliohemerografico(ExpedienteBibliohemerografico expediente)
        {
            var user = HttpContext.Session.GetObject<UserResponse>("ComplexObject");
            expediente.IdUser = user.Id;

            var success = false;
            if (expediente.Id == 0)
            {
                success = await _expedienteRepository.InsertExpedienteBibliohemerografico(expediente);
            }
            else
            {
                success = await _expedienteRepository.UpdateExpedienteBibliohemerografico(expediente);
            }
    
            if (!success)
            {
                TempData["Alert"] = AlertService.ShowAlert(Alerts.Danger, "Ocurrio un error al guardar el expediente");
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> ExpedientesBibliohemerograficos()
        {
            var user = HttpContext.Session.GetObject<UserResponse>("ComplexObject");
            var inventario = await _expedienteRepository.GetInventarioBibliohemerografico(user.Cargo);

            IEnumerable<ExpedienteBibliohemerografico> expedientes = new List<ExpedienteBibliohemerografico>();
            if(inventario != null)
            {
                expedientes = await _expedienteRepository.GetExpedientesBibliohemerograficos(user.Id, inventario.Id);
            }
            return Json(new { data = expedientes });
        }
        [HttpPost]
        public async Task<IActionResult> GetExpedientesBiblioByIdInv([FromForm] int id)
        {
            var user = HttpContext.Session.GetObject<UserResponse>("ComplexObject");
            IEnumerable<ExpedienteBibliohemerografico> expedientes = new List<ExpedienteBibliohemerografico>();
            if(id != 0)
            {
                expedientes = await _expedienteRepository.GetExpedientesBibliohemerograficos(user.Id, id);
            }
            return Json(new { data = expedientes });
        }
        [HttpPost]
        public async Task<IActionResult> DropExpediente(ExpedienteBibliohemerografico expediente)
        {
            var success = await _expedienteRepository.DropExpedienteBibliohemerografico(expediente.Id);
            if (!success)
            {
                TempData["Alert"] = AlertService.ShowAlert(Alerts.Danger, "Ocurrio un error al eliminar el expediente");
                return RedirectToAction("Index");
            }
            TempData["Alert"] = AlertService.ShowAlert(Alerts.Success, "Se eliminó el expediente con exito");
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> GetExpedienteBibliohemerografico([FromForm] int id)
        {
            //ExpedienteBibliohemerografico expediente = new();
            ExpedienteBibliohemerografico expediente = await _expedienteRepository.GetExpedienteBibliohemerografico(id);
            //expediente = await _expedienteRepository.GetExpedienteBibliohemerografico(id);
            var user = HttpContext.Session.GetObject<UserResponse>("ComplexObject");
            if (expediente == null)
            {
                var alert = AlertService.ShowAlert(Alerts.Danger, "Id de expediente no encontrado");
                return Ok(alert);
            }
            expediente.UserName = user.Name;
            return Ok(expediente);
        }
        //[HttpPost]
        //public async Task<IActionResult> SendValExpedienteBiblio(ExpedienteBibliohemerografico expediente)
        //{
        //    var success = await _expedienteRepository.SendValExpedienteBiblio(expediente.Id);
        //    if (!success)
        //    {
        //        TempData["Alert"] = AlertService.ShowAlert(Alerts.Danger, "Ocurrio un error al enviar el expediente bibliohemerográfico");
        //        return RedirectToAction("Index");
        //    }
        //    TempData["Alert"] = AlertService.ShowAlert(Alerts.Success, "Se envió el expediente bibliohemerográfico a revisión con exito");
        //    return RedirectToAction("Index");
        //}
    }
}

ConaviWeb/Controllers/Expedientes/BibliohemerograficoFtoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConaviWeb.Controllers.Expedientes
{
    public class BibliohemerograficoFtoController : Controller
    {
        public IActionResult Index()
        {
            return View("../Expedientes/BibliohemerograficoFto");
        }
    }
}

ConaviWeb/Controllers/Expedientes/InventarioController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ConaviWeb.Commons;
using ConaviWeb.Data.Expedientes;
using ConaviWeb.Model.Expedientes;
using ConaviWeb.Services;
using static ConaviWeb.Models.AlertsViewModel;
using ConaviWeb.Model.Response;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ConaviWeb.Controllers.Expedientes
{
    public class InventarioController : Controller
    {
        private readonly IExpedienteRepository _expedienteRepository;

        public InventarioController(IExpedienteRepository expedienteRepository)
        {
            _expedienteRepository = expedienteRepository;
        }
        public async Task<IActionResult> IndexAsync()
        {
            var user = HttpContext.Session.GetObject<UserResponse>("ComplexObject");
            var idUserPuesto = await _expedienteRepository.GetIdUserPuesto(user.Cargo);
            var inventario = await _expedienteRepository.GetInventarioControl(user.Cargo);
            var cat = await _expedienteRepository.GetCodigosExp();
            ViewData["Catalogo"] = cat;
            //var catPuesto = await _expedienteRepository.GetPuestosLista();
            //ViewBag.AreaCatalogo = (new SelectList(catPuesto, "Id", "Clave", idUserPuesto));
            ViewBag.NombreResponsable = inventario != null ? inventario.NombreResponsableAT : "";
            ViewBag.IdInv = inventario != null ? inventario.Id : 0;
            //ViewBag.FechaElab = inventario != null ? inventario.FechaElaboracion.ToString("dd/MM/yyyy") : "";
            ViewBag.FechaElab = inventario != null ? inventario.FechaElaboracion : "";
            ViewBag.FechaTra = inventario != null ? inventario.FechaTransferencia : "";
            int rol = (int)user.Rol;
            if (rol == 15)
            {
                var catPuesto = await _expedienteRepository.GetPuestosLista();
                ViewBag.AreaCatalogo = (new SelectList(catPuesto, "IdPuesto", "Puesto", idUserPuesto));
                //ViewData["btnShowValidacion"] = true;
            }
            else
            {
                var catPuesto = await _expedienteRepository.GetPuestoUser(idUserPuesto);
                ViewBag.AreaCatalogo = new SelectList(catPuesto, "IdPuesto", "Puesto", idUserPuesto);
                //ViewData["btnShowValidacion"] = false;
            }
            if (TempData.ContainsKey("Alert"))
                ViewBag.Alert = TempData["Alert"].ToString();
            return View("../Expedientes/Inventario");
        }
        [HttpPost]
        public async Task<IActionResult> InsertInventarioTPrimaria(Inventario inventario)
        {
            //var user = HttpContext.Session.GetObject<UserResponse>("ComplexObject");
            //inventario.IdUser = user.Id;
            var success = await _expedienteRepository.InsertInventarioTP(inventario);
            if (!success)
            {
                TempData["Alert"] = AlertService.ShowAlert(Alerts.Danger, "Ocurrio un error al registrar el inventario");
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        //[HttpPost]
        //public async Task<IActionResult> InsertExpedienteInventarioTPrimaria(Expediente expediente)
        //{
        //    var user = HttpContext.Session.GetObject<UserResponse>("ComplexObject");
        //    expediente.IdUser = user.Id;

        //    var success = await _expedienteRepository.InsertExpedienteInventarioTP(expediente);
        //    if (!success)
        //    {
        //        TempData["Alert"] = AlertService.ShowAlert(Alerts.Danger, "Ocurrio un error al registrar el expediente");
        //        return RedirectToAction("Index");
        //    }
        //    return RedirectToAction("Index");
        //}
        [HttpPost]
        public async Task<IActionResult> ExpedientesTP()
        {
            var user = HttpContext.Session.GetObject<UserResponse>("ComplexObject");
            var inventario = await _expedienteRepository.GetInventarioControl(user.Cargo);

            IEnumerable<Expediente> expedientes = new List<Expediente>();
            expedientes = await _expedienteRepository.GetExpedientesInventarioTP(user.Id, inventario!=null ? inventario.Id: 0);
            if (expedientes == null)
            {
                var alert = AlertService.ShowAlert(Alerts.Danger, "Sin registros");
                return Ok(alert);
            }
            return Json(new { data = expedientes });
        }
        [HttpPost]
        public async Task<IActionResult> GetExpedientesTPByIdInv([FromForm] int id)
        {
            IEnumerable<Expediente> expedientes = new List<Expediente>();
            expedientes = await _expedienteRepository.GetExpedientesTPByIdInv(id);
            if (expedientes == null)
            {
                var alert = AlertService.ShowAlert(Alerts.Danger, "Sin registros");
                return Ok(alert);
            }
            return Json(new { data = expedientes });
        }
        //[HttpPost]
        //public async Task<IActionResult> GetExpedienteTP([FromForm] int id)
        //{
        //    Expediente expediente = new();
        //    var user = HttpContext.Session.GetObject<UserResponse>("ComplexObject");
        //    expediente = await _expedienteRepository.GetExpedienteTP(id);
            
        //    if (expediente == null)
        //    {
        //        var alert = AlertService.ShowAlert(Alerts.Danger, "Id de expediente no encontrado");
        //        return Ok(alert);
        //    }
        //    expediente.UserName = user.Name;
        //    return Ok(expediente);
        //}
        [HttpPost]
        public async Task<IActionResult> GetCaratulaExpedienteTP([FromForm] int id, int legajo)
        {
            Caratula caratula = new();
            var user = HttpContext.Session.GetObject<UserResponse>("ComplexObject");
            caratula = await _expedienteRepository.GetCaratulaExpedienteTP(id,legajo);
            
            if (caratula == null)
            {
                var alert = AlertService.ShowAlert(Alerts.Danger, "Id de expediente no encontrado");
                return Ok(alert);
            }
            caratula.UserName = user.Name;
            return Ok(caratula);
        }
        //[HttpPost]
        //public async Task<IActionResult> DropExpediente(Expediente expediente)
        //{
        //    var success = await _expedienteRepository.DropExpediente(expediente.Id);
        //    if (!success)
        //    {
        //        TempData["Alert"] = AlertService.ShowAlert(Alerts.Danger, "Ocurrio un error al eliminar el expediente");
        //        return RedirectToAction("Index");
        //    }
        //    TempData["Alert"] = AlertService.ShowAlert(Alerts.Success, "Se eliminó el expediente con exito");
        //    return RedirectToAction("Index");
        //}
        //[HttpPost]
        //public async Task<IActionResult> SendValExpediente(Expediente expediente)
        //{
        //    var success = await _expedienteRepository.SendValExpediente(expediente.Id);
        //    if (!success)
        //    {
        //        TempData["Alert"] = AlertService.ShowAlert(Alerts.Danger, "Ocurrio un error al enviar el expediente");
        //        return RedirectToAction("Index");
        //    }
        //    TempData["Alert"] = AlertService.ShowAlert(Alerts.Success, "Se envió el expediente a revisión con exito");
        //    return RedirectToAction("Index");
        //}
        //[HttpPost]
        //public async Task<IActionResult> VoBoExpediente(Expediente expediente)
        //{
        //    var success = await _expedienteRepository.VoBoExpediente(expediente.Id);
        //    if (!success)
        //    {
        //        TempData["Alert"] = AlertService.ShowAlert(Alerts.Danger, "Ocurrio un error al enviar el VoBo del expediente");
        //        return RedirectToAction("Index");
        //    }
        //    TempData["Alert"] = AlertService.ShowAlert(Alerts.Success, "Se dió el VoBo al expediente con exito");
        //    return RedirectToAction("Index");
        //}
        //[HttpPost]
        //public async Task<IActionResult> RevalidacionExpediente(Expediente expediente)
        //{
        //    var success = await _expedienteRepository.RevalidacionExpediente(expediente.Id);
        //    if (!success)
        //    {
        //        TempData["Alert"] = AlertService.ShowAlert(Alerts.Danger, "Ocurrio un error al enviar a revalidación el expediente");
        //        return RedirectToAction("Index");
        //    }
        //    TempData["Alert"] = AlertService.ShowAlert(Alerts.Success, "Se envió a revalidación el expediente con exito");
        //    return RedirectToAction("Index");
        //}
    }
}

ConaviWeb/Views/Expedientes/BotonesCatalogos.cshtml
<a class="btn btn-sm btn-primary" target="_self" href="@Url.Action("Index","Catalogos")" title="Catálogo de Serie Documental">
    Catálogo Serie Documental
</a>
<a class="btn btn-sm btn-primary" target="_self" href="@Url.Action("Areas","Catalogos")" title="Catálogo de Áreas">
    Catálogo Áreas
</a>
<a class="btn btn-sm btn-primary" target="_self" href="@Url.Action("Puestos","Catalogos")" title="Catálogo de Puestos">
    Catálogo Puestos
</a>
<a class="btn btn-sm btn-primary" target="_self" href="@Url.Action("Usuarios","Catalogos")" title="Catálogo de Usuarios">
    Catálogo Usuarios
</a>

ConaviWeb/Views/Expedientes/_ActivarSerieDoc.cshtml
@model ConaviWeb.Model.Expedientes.SerieDocumental

<form id="formActivarSerieDoc" enctype="multipart/form-data" method="post" asp-controller="Catalogos" asp-action="ActivarSerieDoc">
    <div class="alert alert-danger" asp-validation-summary="ModelOnly"><button class="close" data-dismiss="alert" aria-hidden="true">&times;</button></div>
    <div class='modal-header'>
        <h4 id='titulo-modal' style="font-weight: 300">Activar Serie Documental</h4>
    </div>
    <div class='modal-body'>
        <input id="idSerieDoc" asp-for="Id" type="text" class="form-control" style="display:none;">
        <div class="row">
            <div class="col-md-12">
                <h3>¿Estás seguro de activar la serie documental?</h3>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">
            <span class="glyphicon glyphicon-ban-circle"></span> Cancelar
        </button>
        <button type="submit" class="btn btn-sm btn-primary active">
            <span class="glyphicon glyphicon-ok-circle"></span> Si, activar
        </button>
    </div>
</form>

ConaviWeb/Views/Expedientes/_AddExpedienteNoExpedientable.cshtml
@model ConaviWeb.Model.Expedientes.ExpedienteNoExpedientable

<!-- Modal -->
<div class="modal fade" id="modalExpediente" tabindex="-1" role="dialog" aria-labelledby="modalExpediente" style="z-index:1041">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Alta de expediente no expedientable</h4>
            </div>
            <form id="formInsertExpedienteNoExpedientable" enctype="multipart/form-data" method="post" asp-controller="NoExpedientable" asp-action="InsertExpedienteNoExpedientable">
                <input type="hidden" id="hd_id_inventario_expediente" asp-for="IdInventario" value="@ViewBag.IdInv" />
                <div class="modal-body">
                    <div class="row form-group">
                        <div class="col-md-4">
                            <label class="control-label" for="slctTipoDocumental">Clave tipo documental:</label>
                            <select asp-for="IdTipoDocumental" id="slctTipoDocumental" class="form-control" asp-items="@(new SelectList((System.Collections.IEnumerable)ViewData["CatTipoDoc"], "Id", "Clave"))">
                                <option value="">--Seleccione--</option>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label class="control-label" for="slctTipoSoporte">Clave tipo de soporte:</label>
                            <select asp-for="IdTipoSoporte" id="slctTipoSoporte" class="form-control" asp-items="@(new SelectList((System.Collections.IEnumerable)ViewData["Catalogo"], "Id", "Clave"))">
                                <option value="">--Seleccione--</option>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label class="control-label" for="text_clave_interna">Clave interna:</label>
                            <select id="slctClaveExp" asp-for="IdClaveInterna" class="form-control" asp-items="@(new SelectList((System.Collections.IEnumerable)ViewData["ClaveInterna"], "Id", "Clave"))">
                                <option value="">--Seleccione--</option>
                            </select>
                        </div>
                        
                    </div>
                    <div class="row form-group">
                        <div class="col-md-4">
                            <label class="control-label" for="text_partes">Número de partes:</label>
                            <input type="number" asp-for="Partes" id="text_partes" placeholder="0" class="form-control" min="1" />
                        </div>
                        <div class="col-md-4 datepicker-group">
                            <label class="control-label" for="felaboracion_nexp">Fecha de Elaboración</label>
                            <input type="text" asp-for="FechaElaboracion" class="form-control" id="felaboracion_nexp" readonly placeholder="yyyy/mm/dd"/>
                            <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-12">
                            <label class="control-label" for="text_titulo">Título del expediente:</label>
                            <input type="text" asp-for="Titulo" id="text_titulo" class="form-control" placeholder="título del expediente..." />
                        </div>
                        <div class="col-md-12">
                            <label class="control-label" for="text_observaciones">Observaciones:</label>
                            <textarea class="form-control" asp-for="Observaciones" id="text_observaciones" placeholder="..." rows="3"></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary">Agregar</button>
                </div>
            </form>
        </div>
    </div>
</div>
@*fin del formulario de expediente de documentacion no expedientable*@

@*<script src="https://framework-gb.cdn.gob.mx/assets/scripts/jquery-ui-datepicker.js"></script>*@
<script type="text/javascript">
    $(document).ready(function () {
        $("#felaboracion_nexp").datepicker({
            dateFormat: 'yy/mm/dd',
            beforeShow: function (input, inst) {
                $(document).off('focusin.bs.modal');
            },
            onClose: function () {
                $(document).on('focusin.bs.modal');
            },
            changeYear: true
        });
        $("#formInsertExpedienteNoExpedientable").submit(function (e) {

            return true;
        });
    });
</script>

ConaviWeb/Views/Expedientes/_AddInventarioBibliohemerografico.cshtml
@model ConaviWeb.Model.Expedientes.Inventario

<form id="formInsertInventarioBibliohemerografico" enctype="multipart/form-data" method="post" asp-controller="Bibliohemerografico" asp-action="InsertInventarioBibliohemerografico">
    <div class="alert alert-danger" asp-validation-summary="ModelOnly"><button class="close" data-dismiss="alert" aria-hidden="true">&times;</button></div>
    <input type="hidden" id="hd_id_inventario" asp-for="Id" value="@ViewBag.IdInv" />
    <div class="row form-group">
        <div class="col-md-8">
            <label class="control-label">Unidad Administrativa:</label>
            <select asp-for="IdPuesto" id="slctPuesto" class="form-control" asp-items="@ViewBag.AreaCatalogo" required>
                <option value="">--Seleccione--</option>
            </select>
        </div>
        <div class="col-md-4 datepicker-group">
            <label for="felaboracion_inventario_biblio">Fecha de elaboración del Inventario:</label>
            <input type="text" id="felaboracion_inventario_biblio" asp-for="FechaElaboracion" value="@ViewBag.FechaElab" class="form-control" placeholder="aaaa/mm/dd" readonly required />
            <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-8">
            <label class="control-label">Nombre del responsable del archivo de trámite:</label>
            <input type="text" id="responsableAT" asp-for="NombreResponsableAT" class="form-control" value="@ViewBag.NombreResponsable" required />
        </div>
        <div class="col-md-4 datepicker-group">
            <label for="ftransferencia_biblio">Fecha de transferencia:</label>
            <input type="text" id="ftransferencia_biblio" asp-for="FechaTransferencia" value="@ViewBag.FechaTrans" class="form-control" placeholder="aaaa/mm/dd" readonly />
            <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12" id="div_btns_inv">
            <button type="submit" id="btn_save_inv" class="btn btn-primary btn-sm pull-right active">
                <span class="fa fa-save"></span> Guardar
            </button>
            <button type="button" id="btn_fto" class="btn btn-sm btn-primary pull-right" title="Formato de Inventario de acervo blibliohemerográfico" onclick="sendToFormat()">
                <span class="fa fa-print"></span> Formato
            </button>
        </div>
    </div>
</form>

<script src="https://framework-gb.cdn.gob.mx/assets/scripts/jquery-ui-datepicker.js"></script>
<script>
    $(document).ready(function () {
        $('#ftransferencia_biblio, #felaboracion_inventario_biblio').datepicker({
            dateFormat: 'yy/mm/dd',
            changeYear: true
        });
        $("#formInsertInventarioBibliohemerografico").submit(function (e) {
            const fecha1 = new Date($("#felaboracion_inventario_biblio").val());
            const fecha2 = new Date($("#ftransferencia_biblio").val());
            if (fecha2 < fecha1) {
                $("#alertAjax").append("<div class='alertaOp alert alert-warning' id='alerta'>La fecha de transferencia no debe ser menor a la fecha de elaboración!</div>");
                showAlert();
                return false;
            }
        });
    });
</script>

ConaviWeb/Views/Expedientes/_DropExpedienteTp.cshtml
@model ConaviWeb.Model.Expedientes.Expediente

<form id="formDropExpediente" enctype="multipart/form-data" method="post" asp-controller="Inventario" asp-action="DropExpediente">
    <div class="alert alert-danger" asp-validation-summary="ModelOnly"><button class="close" data-dismiss="alert" aria-hidden="true">&times;</button></div>
    <div class='modal-header'>
        <h4 id='titulo-modal' style="font-weight: 300">Eliminar Expediente</h4>
    </div>
    <div class='modal-body'>
        <input id="idExpediente" asp-for="Id" type="text" class="form-control" style="display:none;">
        <div class="row">
            <div class="col-md-12">
                <h3>¿Estás seguro de eliminar el expediente?</h3>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn btn-primary">Si, eliminar</button>
    </div>
</form>

ConaviWeb/Views/Expedientes/_RevalidacionExpedienteControl.cshtml
@model ConaviWeb.Model.Expedientes.Expediente

<form id="formVoBoExpediente" enctype="multipart/form-data" method="post">
    <div class="alert alert-danger" asp-validation-summary="ModelOnly"><button class="close" data-dismiss="alert" aria-hidden="true">&times;</button></div>
    <div class='modal-header'>
        <h4 id='titulo-modal' style="font-weight: 300">Revalidación expediente</h4>
    </div>
    <div class='modal-body'>
        <input id="idExpediente" asp-for="Id" type="text" class="form-control" style="display:none;">
        <div class="row">
            <div class="col-md-12">
                <h3>¿Estás seguro de enviar a revalidación el expediente?</h3>
            </div>
            <div class="col-md-12">
                <label for="txt_observaciones_revalidación">Observaciones:</label>
                <input type="text" id="txt_observaciones_revalidacion" class="form-control" />
                <label class="alert alert-danger" id="lbl_error"></label>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">
            <span class="fa fa-ban"></span> Cancelar
        </button>
        <button type="button" id="btn_reval" class="btn btn-sm btn-primary active">
            <span class="fa fa-paper-plane-o"></span> Si, enviar
        </button>
    </div>
</form>